### ISSUE TITLE
Can't initialize

### ISSUE THREAD

**Issue by stagas** [akaspin/nun#2]
Every test and even the example on the readme throw the same error all the time (using node.js version: v0.1.96-8-g3768aaa) (using 'make' all tests fail with this error) :

```
pubuntu@pubuntu:/media/cofs2/nodedev$ node testing.js
crypto:3638
return (new Hash).init(hash);
        ^
TypeError: undefined is not a function
    at CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
    at Object.createHash (crypto:3638:11)
    at /media/cofs2/nodedev/nun/index.js:35:19
    at EventEmitter._tickCallback (node.js:48:25)
    at node.js:204:9
```

---

testing.js is:

```
var sys = require("sys");
var nun = require("./nun");

var origin = "template.html";

nun.render(origin, { name: "John Dow" }, {}, function(err, output){
    if (err) throw err;

    var buffer = '';
    output.addListener('data', function(data){ buffer += data; })
              .addListener('end', function(){ sys.puts(buffer) });
});
```

---

template.html:

```
Name is {{name}}.
```

**Comment by stagas** [comment]
Fixed. It needs ssl libraries installed before compiling node.js for nun to function.
