### ISSUE TITLE
TypeError: Not a string of buffer.

### ISSUE THREAD

**Issue by peterp** [akaspin/nun#7]
```
make
-n test/test-basic.js: 

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Not a string or buffer
    at Array.<anonymous> (/usr/local/lib/node_modules/nun/index.js:35:25)
    at EventEmitter._tickCallback (node.js:126:26)
FAIL
```

Related to this bit of code:

```
if (have_openssl) { 
                // if have openssl, add options hash to key
                key += crypto.createHash("sha1").
                        update(options).digest("hex");
            }
```

I think options is an object, and the update function on on the crypto is looking for a string or buffer.

**Comment by lsm** [comment]
you can checkout the master for fixing this
the npm version is not updated

**Comment by peterp** [comment]
Oh! Sorry about that... Wasn't thinking that it might not be the latest version.
